data:
  dataset_name: imdb_reviews
train:
  buffer_size: 10000
  batch_size: 1024
  vocab_size: 1000
  output_dim: 64
  epochs: 10
  artifact_dir: artifact
  model_dir: models
  checkpoint_dir: ckpt
  tensorboard_log_dir: tb_log_dir
  
